# Statistics Service Configuration Template
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "JobFirst2025!MySQL"
  database: "jobfirst_future"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100
  max_lifetime: "1h"
  log_level: "warn"

redis:
  host: "localhost"
  port: 6379
  password: "JobFirst2025!Redis"
  database: 0
  pool_size: 10

server:
  host: "0.0.0.0"
  port: 8086
  mode: "release"

auth:
  jwt_secret: "jobfirst-unified-auth-secret-key-2024"
  token_expiry: "168h"
  refresh_expiry: "720h"
  password_min_length: 6
  max_login_attempts: 5
  lockout_duration: "30m"

log:
  level: "info"
  format: "json"
  output: "stdout"
  file: "./logs/statistics-service.log"
