# User Service Configuration Template
# This file will be processed during deployment to replace environment-specific values

# MySQL Database Configuration
mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "JobFirst2025!MySQL"
  database: "jobfirst_future"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100
  max_lifetime: "1h"
  log_level: "warn"

# PostgreSQL Database Configuration
postgresql:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "JobFirst2025!PG"
  database: "jobfirst_future"
  sslmode: "disable"
  max_idle: 10
  max_open: 100
  max_lifetime: "1h"

# MongoDB Configuration
mongodb:
  host: "localhost"
  port: 27017
  username: "admin"
  password: "JobFirst2025!Mongo"
  database: "jobfirst"
  auth_source: "admin"

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: "JobFirst2025!Redis"
  database: 0
  pool_size: 10

server:
  host: "0.0.0.0"
  port: 8081
  mode: "release"

auth:
  jwt_secret: "jobfirst-unified-auth-secret-key-2024"
  token_expiry: "168h"
  refresh_expiry: "720h"
  password_min_length: 6
  max_login_attempts: 5
  lockout_duration: "30m"

log:
  level: "info"
  format: "json"
  output: "stdout"
  file: "./logs/user-service.log"
