# User Service 配置文件
# 请根据实际情况修改以下配置

server:
  host: "0.0.0.0"
  port: 8601

consul:
  address: "localhost:8650"
  datacenter: "dc1"

redis:
  address: "localhost:6379"
  password: ""  # Redis密码，如果Redis无密码则留空
  db: 0

database:
  host: "localhost"
  port: 3306
  name: "jobfirst"
  user: "jobfirst"
  password: "jobfirst123"  # MySQL密码，请根据实际情况修改

jwt:
  secret: "your-secret-key"
  expire_hours: 24

logging:
  level: "info"
  format: "json"

# 配置说明：
# 1. Redis密码：如果Redis服务器设置了密码，请填写密码；如果无密码，请留空
# 2. MySQL密码：请填写正确的MySQL用户密码
# 3. 修改后请将文件上传到服务器：/opt/jobfirst/user-service/config.yaml
