# Basic Server Node 2 集群配置
server:
  host: "0.0.0.0"
  port: "8180"
  environment: "development"

cluster:
  # 集群基础配置
  cluster_id: "jobfirst-cluster-1"
  node_id: "basic-server-node-2"
  cluster_manager_url: "http://localhost:9090"
  
  # 节点配置
  node_config:
    host: "localhost"
    port: 8180
    weight: 100
    status: "active"
    metadata:
      service: "basic-server"
      version: "1.0.0"
      mode: "cluster"
      instance: "node-2"

# 数据库配置 (共享)
database:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  name: "jobfirst"
  user: "root"
  password: ""
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

# Redis配置 (共享)
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# JWT配置
jwt:
  secret: "jobfirst-basic-secret-key-2024"
  expires_in: 24h
  refresh_expires_in: 168h
  issuer: "jobfirst-basic"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file: "./logs/basic-server-node2.log"
  max_size: 100
  max_age: 30
  max_backups: 10

# 集群管理配置
cluster_management:
  enabled: true
  heartbeat_interval: 30s
  health_check_interval: 10s
  failure_threshold: 3
  recovery_timeout: 60s
  sync_interval: 5s
