# JobFirst Core Configuration
# 兼容jobfirst-core的配置格式

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "jobfirst"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100
  max_lifetime: "1h"
  log_level: "warn"

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8601
  mode: "release"

# 认证配置
auth:
  jwt_secret: "jobfirst-unified-auth-secret-key-2024"
  token_expiry: "168h"  # 7天，适配测试需要
  refresh_expiry: "720h"  # 30天
  password_min_length: 6
  max_login_attempts: 5
  lockout_duration: "30m"

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"
  file: "./logs/user-service.log"
